#!/bin/bash

if [[ -z "$VIRTUAL_ENV" ]]; then
    # Only activate the virtualenv if we aren't in one already
    source $(which virtualenvwrapper.sh)
    workon argus
fi

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

cd "${SCRIPDIR}"

python argus.py "$@"
