#!/bin/bash

if [[ -z "$VIRTUAL_ENV" ]]; then
    # Only activate the virtualenv if we aren't in one already
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    workon argus
fi

# cd to the argus dir so Argus can find everything it needs
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd "${SCRIPTDIR}"

python argus.py "$@"
